version: '3'

services:
  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    env_file:
      - .env.local
  web:
    build: .
    volumes:
      - .:/app
      - /app/vendor/
    ports:
      - "80:80"
    env_file:
      - .env.local
